### ISSUE TITLE
Video ID not found

### ISSUE THREAD

**Issue by jamesalexyoung** [arthurjarvis02/itvx-adblocker#1]
Firstly thank you for creating/maintaining this extension.

Repeatedly get the following error:

[ITVX Adblocker] Video ID not found

Stack Trace
content.js:43 (anonymous function)

**Comment by arthurjarvis02** [comment]
Could you send a link to the specific episode you are trying to watch? Also, do you have any other chrome extensions running?

**Comment by jamesalexyoung** [comment]
https://www.itv.com/watch/tour-de-france-highlights/10a5559/10a5559a0006

Also running Grammarly and Honey extensions.
ᐧ

**Comment by arthurjarvis02** [comment]
Fix has been implemented into the latest release.

ITV removed the element on the page I was using to grab the video IDs. Also, they changed the key in the local storage that the player stores the breaks watched.

Thanks for using the extension and pointing out the issue :)

**Comment by arthurjarvis02** [comment]
At the moment the extension works when you select a specific episode to watch (your link would work as episode 6 is selected). Will work on getting the ads blocked when clicking play without selecting an episode (eg. [https://www.itv.com/watch/tour-de-france-highlights/10a5559](https://www.itv.com/watch/tour-de-france-highlights/10a5559)), and also for films/one off specials.

**Comment by jamesalexyoung** [comment]
Thanks. Much appreciated. Keep up the good work.
ᐧ

**Comment by arthurjarvis02** [comment]
Issue now fixed when a specific episode is not selected.
